"""
routes/negotiationRoutes.py — FastAPI APIRouter for the AI Negotiation Copilot.

All endpoints return the standard JSON envelope used by the rest of the API:
    { "success": true,  "data": <payload> }   on success
    { "success": false, "message": "<text>" } on error (via HTTPException)

Router is registered in main.py under the prefix /api/negotiation.

Endpoint summary:
    POST /api/negotiation/suggest   → generate an AI negotiation draft

Design:
  - No auth dependency on the suggest endpoint (stateless, no user data stored).
    Add Depends(get_current_user_id) when the auth module is ready if rate-limiting
    or per-user logging is needed in the future.
  - No DB session dependency — the controller is purely computational.
"""

from typing import Optional

from fastapi import APIRouter
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field, field_validator

from controllers.negotiationController import suggest

router = APIRouter(prefix="/api/negotiation", tags=["Negotiation Copilot"])


# ---------------------------------------------------------------------------
# Pydantic request/response schemas
# ---------------------------------------------------------------------------


class NegotiationSuggestRequest(BaseModel):
    """
    Context fields the buyer provides to generate a counter-offer draft.

    All price values are plain numbers — the currency symbol / code is
    supplied separately so the prompt and template can format them correctly.
    """

    vendor_name: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Display name of the vendor being negotiated with.",
        examples=["Acme Steel Supplies Ltd."],
    )
    item_description: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Description of the product or service being priced.",
        examples=["Grade-A Hot-Rolled Steel Coil, 5mm thickness, 500 MT"],
    )
    quoted_price: float = Field(
        ...,
        gt=0,
        description="The price the vendor has quoted (per unit or per lot).",
        examples=[14.50],
    )
    target_price: float = Field(
        ...,
        gt=0,
        description=(
            "The price the buyer wants to achieve. "
            "Must be strictly less than quoted_price."
        ),
        examples=[12.00],
    )
    currency: Optional[str] = Field(
        default="USD $",
        max_length=20,
        description="Currency symbol or code prepended to price values in the draft.",
        examples=["USD $", "EUR €", "GBP £", "PKR ₨"],
    )
    notes: Optional[str] = Field(
        default=None,
        max_length=1000,
        description=(
            "Optional free-text context the buyer wants the AI to factor in "
            "(e.g. 'we have a competing quote at $11.80', 'long-term contract possible')."
        ),
        examples=["We have a competing quote at $11.80 from a certified supplier."],
    )

    @field_validator("vendor_name", "item_description", mode="before")
    @classmethod
    def strip_whitespace(cls, v: str) -> str:
        return v.strip() if isinstance(v, str) else v

    @field_validator("notes", mode="before")
    @classmethod
    def strip_notes(cls, v: Optional[str]) -> Optional[str]:
        if isinstance(v, str):
            stripped = v.strip()
            return stripped if stripped else None
        return v


# ---------------------------------------------------------------------------
# Response envelope helpers (same pattern as messageRoutes / riskRoutes)
# ---------------------------------------------------------------------------


def _ok(data: object, status_code: int = 200) -> JSONResponse:
    """Wrap a payload in the standard success envelope."""
    return JSONResponse(
        status_code=status_code,
        content={"success": True, "data": data},
    )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


@router.post(
    "/suggest",
    summary="Generate an AI negotiation counter-offer draft",
    response_description=(
        "A ready-to-edit negotiation message draft plus context echo and ai_used flag."
    ),
    status_code=200,
)
async def route_suggest(body: NegotiationSuggestRequest) -> JSONResponse:
    """
    **POST /api/negotiation/suggest**

    Accepts negotiation context from the buyer and returns a professional
    counter-offer draft generated by Gemini 2.0 Flash.

    The draft is **plain text** — the buyer can edit it in the frontend panel
    before sending it as a normal chat message via POST /api/messages.
    No new message type is created; the sent message is a standard `text`
    MessageType in the existing conversation thread.

    **Fallback behaviour:**
    If the Gemini API is unavailable (missing key, quota exhausted, network
    error), the endpoint returns a rule-based template that is genuinely usable —
    not an error string. The `ai_used` flag in the response distinguishes the two.

    **Response shape:**
    ```json
    {
      "success": true,
      "data": {
        "draft":   "Dear Acme Steel... (full message text)",
        "ai_used": true,
        "context": {
          "vendor_name":      "Acme Steel Supplies Ltd.",
          "item_description": "Grade-A Hot-Rolled Steel Coil...",
          "quoted_price":     14.50,
          "target_price":     12.00,
          "currency":         "USD $",
          "gap":              2.50,
          "gap_pct":          17.2,
          "notes":            "..."
        }
      }
    }
    ```

    **Validation errors (HTTP 422):**
    - `vendor_name` or `item_description` blank
    - `quoted_price` or `target_price` ≤ 0
    - `target_price` ≥ `quoted_price` (no counter-offer needed)
    """
    data = await suggest(
        vendor_name=body.vendor_name,
        item_description=body.item_description,
        quoted_price=body.quoted_price,
        target_price=body.target_price,
        currency=body.currency or "USD $",
        notes=body.notes,
    )
    return _ok(data)
