import logging
from sqlalchemy import select
from models.vendors import Vendor

logger = logging.getLogger("Seeder")


async def seed_vendors(db):
    result = await db.execute(select(Vendor))
    existing = result.scalars().first()
    if existing:
        logger.info("Vendors already seeded, skipping.")
        return

    vendors = [
        Vendor(
            company_name="Karachi Textile Mills",
            business_description="Cotton garment manufacturer for export.",
            country="Pakistan",
            industry="Textile",
            certification="ISO 9001",
            production_capacity="50,000 units/month",
            export_countries="USA, UK, UAE",
            contact_email="info@karachitextile.com",
            languages="English, Urdu",
            rating=4.5,
            response_time_hours=6,
            is_verified=True,
        ),
        Vendor(
            company_name="Lahore Leather Works",
            business_description="Genuine leather jackets, bags, and accessories manufacturer.",
            country="Pakistan",
            industry="Leather & Apparel",
            certification="ISO 9001",
            production_capacity="15,000 units/month",
            export_countries="Germany, Italy, USA",
            contact_email="sales@lahoreleather.com",
            languages="English, Urdu",
            rating=4.3,
            response_time_hours=8,
            is_verified=True,
        ),
        Vendor(
            company_name="Faisalabad Fabric Co.",
            business_description="Woven and knitted fabric supplier for garment industry.",
            country="Pakistan",
            industry="Textile",
            certification="OEKO-TEX",
            production_capacity="80,000 meters/month",
            export_countries="Bangladesh, Sri Lanka, UK",
            contact_email="contact@faisalabadfabric.com",
            languages="English, Urdu",
            rating=4.1,
            response_time_hours=10,
            is_verified=True,
        ),
        Vendor(
            company_name="Istanbul Steel Works",
            business_description="Stainless steel pipe manufacturer.",
            country="Turkey",
            industry="Metal & Steel",
            certification="ISO 14001",
            production_capacity="10,000 tons/month",
            export_countries="Germany, France, Pakistan",
            contact_email="sales@istanbulsteel.com",
            languages="English, Turkish",
            rating=4.7,
            response_time_hours=4,
            is_verified=True,
        ),
        Vendor(
            company_name="Ankara Metal Fabricators",
            business_description="Custom sheet metal fabrication and CNC machining.",
            country="Turkey",
            industry="Metal & Steel",
            certification="ISO 9001",
            production_capacity="5,000 units/month",
            export_countries="Germany, Netherlands",
            contact_email="info@ankarametal.com",
            languages="English, Turkish",
            rating=4.4,
            response_time_hours=6,
            is_verified=True,
        ),
        Vendor(
            company_name="Shenzhen Solar Tech",
            business_description="Manufacturer of solar inverters and panels.",
            country="China",
            industry="Renewable Energy",
            certification="CE, ISO 14001",
            production_capacity="20,000 units/month",
            export_countries="Pakistan, India, UAE, Africa",
            contact_email="sales@shenzhensolar.com",
            languages="English, Mandarin",
            rating=4.6,
            response_time_hours=5,
            is_verified=True,
        ),
        Vendor(
            company_name="Guangzhou Electronics Ltd.",
            business_description="Consumer electronics and accessories manufacturer.",
            country="China",
            industry="Electronics",
            certification="CE, RoHS",
            production_capacity="100,000 units/month",
            export_countries="Worldwide",
            contact_email="export@gzelectronics.com",
            languages="English, Mandarin",
            rating=4.2,
            response_time_hours=3,
            is_verified=True,
        ),
        Vendor(
            company_name="Yiwu Household Goods Co.",
            business_description="Wholesale supplier of household and kitchen items.",
            country="China",
            industry="Household Goods",
            certification="ISO 9001",
            production_capacity="200,000 units/month",
            export_countries="Worldwide",
            contact_email="info@yiwuhousehold.com",
            languages="English, Mandarin",
            rating=4.0,
            response_time_hours=12,
            is_verified=False,
        ),
        Vendor(
            company_name="Dubai Trading & Logistics",
            business_description="Import/export trading hub for FMCG and industrial goods.",
            country="UAE",
            industry="Trading",
            certification="ISO 9001",
            production_capacity="N/A - Trading Company",
            export_countries="GCC, South Asia, Africa",
            contact_email="deals@dubaitrading.com",
            languages="English, Arabic",
            rating=4.3,
            response_time_hours=4,
            is_verified=True,
        ),
        Vendor(
            company_name="Sharjah Plastic Industries",
            business_description="Injection-molded plastic products manufacturer.",
            country="UAE",
            industry="Plastics",
            certification="ISO 9001",
            production_capacity="30,000 units/month",
            export_countries="GCC, Pakistan, India",
            contact_email="sales@sharjahplastic.com",
            languages="English, Arabic",
            rating=3.9,
            response_time_hours=9,
            is_verified=False,
        ),
        Vendor(
            company_name="Dhaka Garments Export",
            business_description="Mass-scale garment manufacturer for global fashion brands.",
            country="Bangladesh",
            industry="Textile",
            certification="ISO 9001, BSCI",
            production_capacity="150,000 units/month",
            export_countries="USA, UK, EU",
            contact_email="export@dhakagarments.com",
            languages="English, Bengali",
            rating=4.4,
            response_time_hours=7,
            is_verified=True,
        ),
        Vendor(
            company_name="Ho Chi Minh Furniture Co.",
            business_description="Wooden and rattan furniture manufacturer.",
            country="Vietnam",
            industry="Furniture",
            certification="FSC Certified",
            production_capacity="8,000 units/month",
            export_countries="USA, Japan, Australia",
            contact_email="info@hcmfurniture.com",
            languages="English, Vietnamese",
            rating=4.5,
            response_time_hours=10,
            is_verified=True,
        ),
        Vendor(
            company_name="Mumbai Spice Exports",
            business_description="Bulk spice and agro-commodity exporter.",
            country="India",
            industry="Food & Agriculture",
            certification="FSSAI, ISO 22000",
            production_capacity="500 tons/month",
            export_countries="Middle East, Europe",
            contact_email="sales@mumbaispice.com",
            languages="English, Hindi",
            rating=4.2,
            response_time_hours=6,
            is_verified=True,
        ),
        Vendor(
            company_name="Bangalore Auto Parts Ltd.",
            business_description="OEM and aftermarket automotive parts manufacturer.",
            country="India",
            industry="Automotive",
            certification="ISO/TS 16949",
            production_capacity="40,000 units/month",
            export_countries="Middle East, Africa, Southeast Asia",
            contact_email="export@bangaloreauto.com",
            languages="English, Hindi",
            rating=4.1,
            response_time_hours=8,
            is_verified=True,
        ),
        Vendor(
            company_name="Hamburg Industrial Supplies",
            business_description="Industrial equipment and machinery parts supplier.",
            country="Germany",
            industry="Industrial Equipment",
            certification="ISO 9001, CE",
            production_capacity="3,000 units/month",
            export_countries="EU, Middle East",
            contact_email="contact@hamburgindustrial.de",
            languages="English, German",
            rating=4.8,
            response_time_hours=5,
            is_verified=True,
        ),
    ]

    db.add_all(vendors)
    await db.commit()
    logger.info(f"✅ Seeded {len(vendors)} vendors.")