"""
models/Conversation.py — SQLAlchemy ORM model for a chat conversation thread.

A Conversation is the container for a set of Messages between two or more
participants.  The messaging module queries conversations to build the
inbox/conversation-list view.
"""

from sqlalchemy import Column, DateTime, text
from sqlalchemy.dialects.postgresql import ARRAY, UUID
from sqlalchemy.sql import func

from backend.database.base import Base


class Conversation(Base):
    """A chat thread between two or more participants."""

    __tablename__ = "conversations"

    # ------------------------------------------------------------------
    # Primary key — UUID generated by PostgreSQL (no Python round-trip).
    # ------------------------------------------------------------------
    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        nullable=False,
    )

    # ------------------------------------------------------------------
    # V1 DESIGN DECISION — PostgreSQL ARRAY vs. join table
    # ------------------------------------------------------------------
    # participant_ids is stored as a PostgreSQL ARRAY of UUIDs rather than
    # a separate `conversation_participants` join table.
    #
    # Pros (v1 simplicity):
    #   • Single-column reads — no join needed to fetch participants.
    #   • Efficient for the primary messaging query:
    #       WHERE user_id = ANY(participant_ids)
    #
    # Cons / tradeoff to document:
    #   • A join table would be more relationally queryable for admin/fraud
    #     lookups (e.g. "find all conversations involving user X", "count
    #     distinct participants across threads for fraud scoring") because
    #     those access patterns can use a standard indexed JOIN instead of
    #     scanning an ARRAY column.
    #   • Updating participants (add/remove) requires rewriting the whole
    #     array rather than a targeted INSERT/DELETE on a join row.
    #
    # Recommendation: migrate to a `conversation_participants` join table
    # in v2 if admin reporting, fraud tooling, or participant management
    # becomes a requirement.
    # ------------------------------------------------------------------
    participant_ids = Column(
        ARRAY(UUID(as_uuid=True)),
        nullable=False,
        server_default=text("'{}'::uuid[]"),
        comment=(
            "V1: PostgreSQL ARRAY of participant UUIDs.  "
            "See inline design-decision note — consider a join table for v2 "
            "if admin/fraud or participant-management queries are needed."
        ),
    )

    # ------------------------------------------------------------------
    # Timestamps
    # ------------------------------------------------------------------
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        # SQLAlchemy fires onupdate on ORM-level updates; raw SQL UPDATE
        # statements must set this column explicitly.
        onupdate=func.now(),
    )

    # Nullable: NULL until the first message is sent in this conversation.
    # Used to sort the inbox by most-recent activity.
    last_message_at = Column(
        DateTime(timezone=True),
        nullable=True,
    )
